export const ERROR_MESSAGES = {
	cannotAuthenticate: "Cannot authenticate",
	wrongEmailOrPassword: "Wrong email or password",
	notAuthorized: "Not authorized",
	wrongPayload: "Wrong payload",
	generalError: "Something went wrong",
	failedToUpdate: "Failed to update",
	failedToCreate: "Failed to create",
	failedToDelete: "Failed to delete",
	failedToRemove: "Failed to remove",
	failedToInviteAlreadyExists: "Failed to invite, user already exists",
	failedToInvite: "Failed to invite",
	failedToAccept: "Failed to accept",
	failedToGetClientInfo: "Failed to get client info",
	failedToUpdateLogVersionMismatch: "Failed to update log",
	failedToCreateLogVersionMismatch: "Could not update log",
	conflictingLogAlreadyExists: "Conflicting log already exists",
	generalAlreadyExists: "Already exists",
	notFound: "Not found",
	tagIdRequired: "Tag ID is required",
	userNotFound: "User not found",
	userSessionMissing: "User session missing",
	userIdRequired: "User ID is required",
	notAdmin: "User is not an admin",
	projectIdRequired: "Project ID is required",
	projectNotFound: "Project not found",
	unsupportedContentType: "Unsupported content type",
	memberIdRequired: "Member ID is required",
	clientNotFound: "Client not found",
	clientIdRequired: "Client ID is required",
};
