export enum ROUTES {
	projects = "/projects",
	project = "/projects/",
	projectTeamMember = "/projects/:projectId/team/:teamMemberId",
	projectStatistics = "/projects/:projectId/statistics",
	createProject = "/projects/create",
	login = "/login",
	logout = "/logout",
	register = "/register",
	profile = "/profile",
	admin = "/admin",
	myActivities = "/my-activities",
	inbox = "/inbox",
	notFound = "/404",
}
